import { env } from './storage';
import { EventError, eventHandler, eventJson, positiveId } from './practice-parties-server';
import { parseFreeEvent, parseMeeting } from './free-events';

export { EventError, eventHandler, eventJson, positiveId };
export async function eventAccess(request: Request) {
  const hostname = new URL(request.url).hostname;
  const local = ['localhost', '127.0.0.1', '[::1]'].includes(hostname);
  const email = request.headers.get('cf-access-authenticated-user-email')?.trim().toLowerCase() || (local ? 'administrator@local' : '');
  if (!email) throw new EventError('Sign in to manage free events.', 401);
  if (local || email === 'croitoriu.alexandru.code@gmail.com') return { email };
  const permission = await env.DB.prepare('SELECT can_free_events FROM administrator_permissions WHERE email = ?').bind(email).first<{ can_free_events: number }>();
  if (permission?.can_free_events !== 1) throw new EventError('You do not have permission to manage free events.', 403);
  return { email };
}
const eventColumns = `e.id, e.name, e.starts_on AS startsOn, e.ends_on AS endsOn, e.image_path AS imagePath, e.revision, (SELECT COUNT(*) FROM free_event_meetings m WHERE m.event_id = e.id) AS meetingCount`;
const meetingColumns = `m.id, m.event_id AS eventId, m.name, m.starts_at AS startsAt, m.starts_utc AS startsUtc, m.duration_minutes AS durationMinutes, m.space_rent_minor AS spaceRentMinor, m.accepts_donations AS acceptsDonations, m.cancelled, m.revision, (SELECT COUNT(*) FROM free_event_attendance a WHERE a.meeting_id = m.id) AS attendanceCount`;
function originChecked(request: Request) { const origin = request.headers.get('Origin'); if (origin && origin !== new URL(request.url).origin) throw new EventError('Cross-origin writes are not allowed.', 403); }
async function input(request: Request) { originChecked(request); if (!request.headers.get('Content-Type')?.startsWith('application/json')) throw new EventError('Send JSON event details.', 415); const body = await request.json().catch(() => null) as Record<string, unknown> | null; if (!body || typeof body.action !== 'string') throw new EventError('Invalid save request.'); return body; }
const snapshotEvent = (x: Record<string, unknown>) => JSON.stringify({ name: x.name, startsOn: x.startsOn ?? x.starts_on ?? null, endsOn: x.endsOn ?? x.ends_on ?? null, imagePath: x.imagePath ?? x.image_path ?? null });
const snapshotMeeting = (x: Record<string, unknown>) => JSON.stringify({ name: x.name, startsAt: x.startsAt ?? x.starts_at, durationMinutes: x.durationMinutes ?? x.duration_minutes, spaceRentMinor: x.spaceRentMinor ?? x.space_rent_minor, acceptsDonations: x.acceptsDonations ?? x.accepts_donations, cancelled: x.cancelled ?? 0 });

async function removeUnusedEventImage(path: unknown) {
  // This bucket also contains private student photos: only delete event-upload keys.
  if (typeof path !== 'string') return;
  const match = /^\/api\/free-event-images\/(free-event-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.jpg)$/.exec(path);
  if (!match) return;
  const referenced = await env.DB.prepare('SELECT id FROM free_events WHERE image_path = ? LIMIT 1').bind(path).first();
  if (!referenced) await env.STUDENT_IMAGES.delete(match[1]);
}

export async function freeEvents() { const result = await env.DB.prepare(`SELECT ${eventColumns} FROM free_events e ORDER BY COALESCE(e.starts_on, '9999-12-31'), e.name COLLATE NOCASE, e.id`).all(); return result.results; }
export async function freeEvent(id: number) { const event = await env.DB.prepare(`SELECT ${eventColumns} FROM free_events e WHERE e.id = ?`).bind(id).first<Record<string, unknown>>(); if (!event) throw new EventError('Free event not found.', 404); const meetings = await env.DB.prepare(`SELECT ${meetingColumns} FROM free_event_meetings m WHERE m.event_id = ? ORDER BY m.starts_at, m.id`).bind(id).all(); return { event, meetings: meetings.results }; }
export async function createOrUpdateEvent(request: Request, id?: number) { const { email } = await eventAccess(request), body = await input(request), now = new Date().toISOString();
  await env.DB.prepare("INSERT INTO admin_profiles (email, name) VALUES (?, '') ON CONFLICT(email) DO NOTHING").bind(email).run();
  if (id === undefined) { if (body.action !== 'create') throw new EventError('Invalid event action.'); const details = parseFreeEvent(body.event); const result = await env.DB.prepare('INSERT INTO free_events (name, starts_on, ends_on, image_path, created_by, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id').bind(details.name, details.startsOn, details.endsOn, details.imagePath, email, now, now).first<{ id: number }>(); await env.DB.prepare('INSERT INTO free_event_change_log (event_id, administrator_email, action, after_json, created_at) VALUES (?, ?, ?, ?, ?)').bind(result!.id, email, 'created', snapshotEvent(details), now).run(); return eventJson({ id: result!.id }, 201); }
  const existing = await env.DB.prepare('SELECT * FROM free_events WHERE id = ?').bind(id).first<Record<string, unknown>>(); if (!existing) throw new EventError('Free event not found.', 404); if (!Number.isInteger(body.revision) || body.revision !== existing.revision) throw new EventError('This event changed. Reload before saving.', 409); if (body.action === 'delete') { const deleted = await env.DB.prepare('DELETE FROM free_events WHERE id = ? AND revision = ?').bind(id, existing.revision).run(); if (!deleted.meta.changes) throw new EventError('This event changed. Reload before deleting.', 409); await removeUnusedEventImage(existing.image_path); return eventJson({ id }); }
  if (body.action !== 'update') throw new EventError('Invalid event action.'); const details = parseFreeEvent(body.event); const changed = await env.DB.prepare('UPDATE free_events SET name = ?, starts_on = ?, ends_on = ?, image_path = ?, revision = revision + 1, updated_at = ? WHERE id = ? AND revision = ?').bind(details.name, details.startsOn, details.endsOn, details.imagePath, now, id, existing.revision).run(); if (!changed.meta.changes) throw new EventError('This event changed. Reload before saving.', 409); await env.DB.prepare('INSERT INTO free_event_change_log (event_id, administrator_email, action, before_json, after_json, created_at) VALUES (?, ?, ?, ?, ?, ?)').bind(id, email, 'updated', snapshotEvent(existing), snapshotEvent(details), now).run(); if (existing.image_path !== details.imagePath) await removeUnusedEventImage(existing.image_path); return eventJson({ id });
}
export async function mutateMeeting(request: Request, eventId: number, meetingId?: number) { const { email } = await eventAccess(request), body = await input(request), now = new Date().toISOString(); if (!await env.DB.prepare('SELECT id FROM free_events WHERE id = ?').bind(eventId).first()) throw new EventError('Free event not found.', 404);
  await env.DB.prepare("INSERT INTO admin_profiles (email, name) VALUES (?, '') ON CONFLICT(email) DO NOTHING").bind(email).run();
  if (meetingId === undefined) { if (body.action !== 'create') throw new EventError('Invalid meeting action.'); const details = parseMeeting(body.meeting); const result = await env.DB.prepare('INSERT INTO free_event_meetings (event_id, name, starts_at, starts_utc, duration_minutes, space_rent_minor, accepts_donations, created_by, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id').bind(eventId, details.name, details.startsAt, details.startsUtc, details.durationMinutes, details.spaceRentMinor, details.acceptsDonations, email, now, now).first<{ id: number }>(); await env.DB.prepare('INSERT INTO free_meeting_change_log (meeting_id, administrator_email, action, after_json, created_at) VALUES (?, ?, ?, ?, ?)').bind(result!.id, email, 'created', snapshotMeeting(details), now).run(); return eventJson({ id: result!.id }, 201); }
  const existing = await env.DB.prepare('SELECT * FROM free_event_meetings WHERE id = ? AND event_id = ?').bind(meetingId, eventId).first<Record<string, unknown>>(); if (!existing) throw new EventError('Meeting not found.', 404); if (!Number.isInteger(body.revision) || body.revision !== existing.revision) throw new EventError('This meeting changed. Reload before saving.', 409); if (body.action === 'delete') { await env.DB.prepare('DELETE FROM free_event_meetings WHERE id = ? AND revision = ?').bind(meetingId, existing.revision).run(); return eventJson({ id: meetingId }); }
  if (body.action !== 'update') throw new EventError('Invalid meeting action.'); const details = parseMeeting(body.meeting); const changed = await env.DB.prepare('UPDATE free_event_meetings SET name = ?, starts_at = ?, starts_utc = ?, duration_minutes = ?, space_rent_minor = ?, accepts_donations = ?, revision = revision + 1, updated_at = ? WHERE id = ? AND revision = ?').bind(details.name, details.startsAt, details.startsUtc, details.durationMinutes, details.spaceRentMinor, details.acceptsDonations, now, meetingId, existing.revision).run(); if (!changed.meta.changes) throw new EventError('This meeting changed. Reload before saving.', 409); await env.DB.prepare('INSERT INTO free_meeting_change_log (meeting_id, administrator_email, action, before_json, after_json, created_at) VALUES (?, ?, ?, ?, ?, ?)').bind(meetingId, email, 'updated', snapshotMeeting(existing), snapshotMeeting(details), now).run(); return eventJson({ id: meetingId });
}
