/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.local.json --include-runtime=false --env-interface=LocalDevelopmentBindings local-configuration.d.ts` (hash: c3a437bc628fd5550276994023f28247)
interface __BaseEnv_LocalDevelopmentBindings {
	CATALOG_IMAGES: R2Bucket;
	WORKING_IMAGES: R2Bucket;
	PRODUCTION_IMAGES: R2Bucket;
	COPY2_IMAGES: R2Bucket;
	COPY3_IMAGES: R2Bucket;
	COPY4_IMAGES: R2Bucket;
	COPY5_IMAGES: R2Bucket;
	COPY6_IMAGES: R2Bucket;
	COPY7_IMAGES: R2Bucket;
	COPY8_IMAGES: R2Bucket;
	LOCAL_BACKUP_BUCKET: R2Bucket;
	CATALOG_DB: D1Database;
	WORKING_DB: D1Database;
	PRODUCTION_DB: D1Database;
	COPY2_DB: D1Database;
	COPY3_DB: D1Database;
	COPY4_DB: D1Database;
	COPY5_DB: D1Database;
	COPY6_DB: D1Database;
	COPY7_DB: D1Database;
	COPY8_DB: D1Database;
	CLOUDFLARE_ACCESS_CLIENT_ID: string;
	CLOUDFLARE_ACCESS_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_LocalDevelopmentBindings {}
}
interface LocalDevelopmentBindings extends __BaseEnv_LocalDevelopmentBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLOUDFLARE_ACCESS_CLIENT_ID" | "CLOUDFLARE_ACCESS_CLIENT_SECRET">> {}
}
