/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.local.json --include-runtime=false --env-interface=LocalDevelopmentBindings local-configuration.d.ts` (hash: c069401203c4fce1364a9d8ac2f83e90)
interface __BaseEnv_LocalDevelopmentBindings {
	CATALOG_IMAGES: R2Bucket;
	CATALOG_DB: D1Database;
	CLOUDFLARE_ACCESS_CLIENT_ID: string;
	CLOUDFLARE_ACCESS_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_LocalDevelopmentBindings {}
}
interface LocalDevelopmentBindings extends __BaseEnv_LocalDevelopmentBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLOUDFLARE_ACCESS_CLIENT_ID" | "CLOUDFLARE_ACCESS_CLIENT_SECRET">> {}
}
