'use client';
import { useEffect, useRef, useState } from 'react';
import { requestJson } from '../lib/http';
import { eventButton as button, eventInput as input, eventPrimary as primary, sessionEnd, type EventDetail, type PracticeSession, type EventStudent, type EventPayment } from '../lib/practice-parties';
import { formatLogDate, formatMoney, schoolToday } from '../lib/student-activity';
import { SessionFields, useEventSave, type SessionDraft } from './practice-forms';

type Action = { kind: string; session?: PracticeSession; student?: EventStudent; payment?: EventPayment };
export default function PracticePartyPanel({ id, onClose, initialTab }: { id: number; onClose: () => void; initialTab?: 'form' | 'attendance' | 'donations' }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [data, setData] = useState<EventDetail | null>(null), [error, setError] = useState(''), [reload, setReload] = useState(0), [action, setAction] = useState<Action | null>(null), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false), [tab, setTab] = useState<'form' | 'attendance' | 'donations'>(initialTab ?? 'attendance');
  useEffect(() => { const element = dialog.current, overflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; element?.showModal(); return () => { element?.close(); document.body.style.overflow = overflow; }; }, []);
  useEffect(() => { const controller = new AbortController(); setError(''); requestJson<EventDetail>(`/api/practice-parties/${id}`, { signal: controller.signal }).then(d => { if (!controller.signal.aborted) setData(d); }).catch(e => { if (!controller.signal.aborted) setError(e.message); }); return () => controller.abort(); }, [id, reload]);
  function saved() { setAction(null); setNotice('Saved.'); setReload(v => v + 1); }
  return <dialog ref={dialog} aria-label="Practice party" className="fixed inset-y-0 right-0 left-auto m-0 h-dvh max-h-none w-full max-w-3xl overflow-y-auto border-0 bg-stone-50 p-0 text-slate-800 shadow-2xl backdrop:bg-slate-950/60" onCancel={e => { e.preventDefault(); if (!busy) onClose(); }} onClick={event => { if (event.target !== event.currentTarget) return; const bounds = event.currentTarget.getBoundingClientRect(); if (event.clientX < bounds.left || event.clientX > bounds.right || event.clientY < bounds.top || event.clientY > bounds.bottom) onClose(); }}>
    <div className="sticky top-0 z-10 flex items-center justify-between border-b border-stone-200 bg-white p-5"><h1 className="m-0 text-2xl">Practice party</h1><button className={button} aria-label="Close practice party panel" disabled={busy} onClick={onClose}>Close</button></div>
    <div className="space-y-5 p-5">
    {error && <p role="alert" className="text-red-700">{error} <button className={button} onClick={() => setReload(v => v + 1)}>Reload</button></p>}{notice && <p role="status" className="text-lime-800">{notice}</p>}
    {!data ? <p>Loading practice party…</p> : <>
      <p className="font-sans text-sm">{formatLogDate(data.party.startsAt)} → {formatLogDate(sessionEnd(data.party))} · {data.party.durationMinutes} minutes · Bucharest time</p>
      <nav aria-label="Practice party sections" className="flex gap-5 border-b border-stone-200"><button type="button" className={`border-b-2 px-1 py-3 font-sans text-sm font-semibold ${tab === 'form' ? 'border-lime-600 text-slate-800' : 'border-transparent text-slate-500'}`} onClick={() => setTab('form')}>Practice party</button><button type="button" className={`border-b-2 px-1 py-3 font-sans text-sm font-semibold ${tab === 'attendance' ? 'border-lime-600 text-slate-800' : 'border-transparent text-slate-500'}`} onClick={() => setTab('attendance')}>Attendance</button>{data.permissions.finance && <button type="button" className={`border-b-2 px-1 py-3 font-sans text-sm font-semibold ${tab === 'donations' ? 'border-lime-600 text-slate-800' : 'border-transparent text-slate-500'}`} onClick={() => setTab('donations')}>Donations</button>}</nav>
      {tab === 'form' && <EventAction key={`edit-${data.party.id}-${data.party.revision}`} data={data} action={{ kind: 'edit_session', session: data.party }} saved={() => { setNotice('Saved.'); setReload(v => v + 1); }} setParentBusy={setBusy} close={onClose} />}
      {tab === 'attendance' && data.permissions.roster && <Roster id={id} session={data.party} finance={data.permissions.finance} reload={reload} refresh={() => setReload(v => v + 1)} />}
      {tab === 'donations' && data.permissions.finance && <section className="space-y-4 rounded-xl border border-stone-200 bg-white p-5"><h2 className="text-xl">Donations</h2>
        <div className="flex flex-wrap gap-4 font-sans text-sm"><span>Received: <strong>{formatMoney(data.totals.receivedMinor)}</strong></span><span>Given to school: <strong>{formatMoney(data.totals.givenMinor)}</strong></span><span>Not yet given: <strong>{formatMoney(data.totals.pendingMinor)}</strong></span></div>
        <div className="space-y-3">{data.payments.map(p => <article key={p.id} className="rounded-lg border border-stone-200 p-3 font-sans text-sm"><div className="flex flex-wrap justify-between gap-2"><a className="underline" href={`/students/${p.studentId}`}>{p.studentName || 'Student'}</a><strong>{formatMoney(p.amountMinor)}</strong></div><p className="text-xs">{formatLogDate(p.paidOn)} · Collected by {p.recordedBy}</p>{p.notes && <p className="whitespace-pre-wrap">{p.notes}</p>}<p className="text-xs">{p.givenToSchool ? 'Given to school' : 'Not yet given to school'}</p><div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={() => setAction({ kind: 'edit_donation', payment: p })}>Edit donation</button><button className={button} disabled={busy} onClick={() => setAction({ kind: 'delete_donation', payment: p })}>Delete donation</button><button className={button} disabled={busy} onClick={() => setAction({ kind: 'handover', payment: p })}>{p.givenToSchool ? 'Undo school transfer' : 'Give to school'}</button></div></article>)}{!data.payments.length && <p>No donations recorded.</p>}</div>
      </section>}
      {tab === 'donations' && action && <EventAction key={`${action.kind}-${action.student?.id}-${action.payment?.id}`} data={data} action={action} saved={saved} setParentBusy={setBusy} close={() => { setAction(null); setReload(v => v + 1); }} />}
    </>}
    </div>
  </dialog>;
}
function Roster({ id, session, finance, reload, refresh }: { id: number; session: PracticeSession; finance: boolean; reload: number; refresh: () => void }) {
  const [q, setQ] = useState(''), [page, setPage] = useState(1), [data, setData] = useState<{ students: EventStudent[]; count: number } | null>(null), [error, setError] = useState(''), [selected, setSelected] = useState<number[]>([]), [donations, setDonations] = useState<Record<number, string>>({});
  const mutation = useEventSave(`/api/practice-parties/${id}`, () => { setSelected([]); setDonations({}); refresh(); });
  useEffect(() => { const controller = new AbortController(); setError(''); const timer = setTimeout(() => { requestJson<{ students: EventStudent[]; count: number }>(`/api/practice-parties/${id}/roster?${new URLSearchParams({ q, page: String(page) })}`, { signal: controller.signal }).then(d => { if (!controller.signal.aborted) { setData(d); setSelected([]); setDonations({}); } }).catch(e => { if (!controller.signal.aborted) setError(e.message); }); }, 150); return () => { clearTimeout(timer); controller.abort(); }; }, [id, session.id, q, page, reload]);
  const editable = !session.cancelled;
  const changed = selected.length + Object.values(donations).filter(Boolean).length;
  const active = data?.students.filter(student => student.active) ?? [], inactive = data?.students.filter(student => !student.active) ?? [];
  function toggle(studentId: number) { setSelected(ids => ids.includes(studentId) ? ids.filter(id => id !== studentId) : [...ids, studentId]); }
  function save() { if (!data || !changed || !editable) return; const addStudentIds = selected.filter(studentId => !data.students.find(student => student.id === studentId)?.attendanceId), removeAttendanceIds = selected.map(studentId => data.students.find(student => student.id === studentId)).filter((student): student is EventStudent => !!student?.attendanceId).map(student => student.attendanceId!), donationRows = Object.entries(donations).filter(([, amount]) => amount.trim()).map(([studentId, amount]) => ({ studentId: Number(studentId), amount })); void mutation.save({ action: 'attendance_batch', revision: session.revision, addStudentIds, removeAttendanceIds, donations: donationRows }); }
  function card(student: EventStudent) { const changedAttendance = selected.includes(student.id), green = Boolean(student.attendanceId) !== changedAttendance; return <div key={student.id} className={`flex items-center gap-2 overflow-hidden rounded-xl border ${green ? 'border-green-500 bg-green-50 text-green-900' : 'border-stone-200 bg-white hover:border-green-400'}`}><button type="button" aria-pressed={green} disabled={!editable || mutation.busy} onClick={() => toggle(student.id)} className="flex min-w-0 flex-1 items-center gap-3 border-0 bg-transparent p-3 text-left focus:outline-none focus:ring-2 focus:ring-inset focus:ring-green-600"><span className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-full bg-lime-200 font-sans font-bold text-slate-800">{student.picture ? <img alt="" src={student.picture} className="h-full w-full object-cover" /> : `${student.firstName[0] ?? ''}${student.lastName[0] ?? ''}`}</span><span className="min-w-0 flex-1"><span className="block truncate font-sans text-sm font-semibold">{`${student.firstName} ${student.lastName}`.trim() || student.email || 'Student'}</span>{!student.active && <span className="mt-1 block font-sans text-xs text-slate-500">Inactive</span>}</span><span className="hidden font-sans text-xs font-semibold sm:block">{changedAttendance ? (student.attendanceId ? 'Remove on submit' : '✓ Selected') : student.attendanceId ? '✓ Recorded' : 'Select'}</span></button>{finance && <label className="w-28 shrink-0 pr-3 font-sans text-xs">Donation (RON)<input aria-label={`Donation for ${student.firstName} ${student.lastName}`} disabled={!editable || mutation.busy} inputMode="decimal" pattern="[0-9]{1,6}([.,][0-9]{1,2})?" className="mt-1 w-full rounded-md border border-stone-300 bg-white p-2 text-sm text-slate-800" value={donations[student.id] ?? ''} onChange={event => setDonations(current => ({ ...current, [student.id]: event.target.value }))} /></label>}</div>; }
  return <section className="space-y-5"><div className="flex flex-wrap items-center gap-4"><label className="font-sans text-sm">Find a student<input type="search" className={input} value={q} onChange={e => { setQ(e.target.value); setPage(1); }} /></label><a href="/students" className="text-sm underline">Add a student</a></div>{error && <p role="alert" className="text-red-700">{error}</p>}{mutation.error && <p role="alert" className="text-red-700">{mutation.error}</p>}{session.cancelled && <p className="rounded-lg bg-red-50 p-3 font-sans text-sm text-red-700">This practice party is cancelled. Attendance cannot be changed.</p>}{data && <><section aria-labelledby="active-students-title"><h2 id="active-students-title" className="mb-3 text-xl font-normal">Active students ({active.length})</h2><div className="space-y-2">{active.map(card)}</div>{!active.length && <p className="font-sans text-sm text-slate-500">No active students match.</p>}</section><section aria-labelledby="other-students-title"><h2 id="other-students-title" className="mb-3 text-xl font-normal">Other students ({inactive.length})</h2><div className="space-y-2">{inactive.map(card)}</div>{!inactive.length && <p className="font-sans text-sm text-slate-500">No other students match.</p>}</section></>}<nav aria-label="Participant pages" className="flex items-center justify-between"><button className={button} disabled={page <= 1 || mutation.busy} onClick={() => setPage(p => p - 1)}>Previous</button><span className="text-sm">Page {page} of {Math.max(1, Math.ceil((data?.count ?? 0) / 100))}</span><button className={button} disabled={!data || page * 100 >= data.count || mutation.busy} onClick={() => setPage(p => p + 1)}>Next</button></nav><footer className="sticky bottom-0 flex items-center justify-between gap-4 border-t border-stone-200 bg-white py-5"><p className="m-0 font-sans text-xs text-slate-500">{changed} changes · {data?.students.filter(student => student.attendanceId).length ?? 0} recorded on this page</p><button type="button" className={primary} disabled={!editable || mutation.busy || !data || !changed} onClick={save}>{mutation.busy ? 'Saving…' : mutation.uncertain ? 'Retry same save' : 'Submit attendance'}</button></footer></section>;
}
function EventAction({ data, action, saved, close, setParentBusy }: { data: EventDetail; action: Action; saved: () => void; close: () => void; setParentBusy: (busy: boolean) => void }) {
  const { kind, session, student, payment } = action;
  const draft: SessionDraft = { date: data.party.startsAt.slice(0, 10), time: data.party.startsAt.slice(11, 16), durationMinutes: data.party.durationMinutes, offset: '' };
  const [schedule, setSchedule] = useState(draft), [amount, setAmount] = useState(payment ? (payment.amountMinor / 100).toFixed(2) : ''), [date, setDate] = useState(payment?.paidOn ?? schoolToday()), [reason, setReason] = useState(payment?.notes ?? '');
  const mutation = useEventSave(`/api/practice-parties/${data.party.id}`, saved);
  const form = useRef<HTMLFormElement>(null);
  useEffect(() => { form.current?.scrollIntoView({ block: 'start', behavior: 'smooth' }); form.current?.querySelector<HTMLElement>('input,textarea,button')?.focus({ preventScroll: true }); }, []);
  useEffect(() => { setParentBusy(mutation.busy); return () => setParentBusy(false); }, [mutation.busy, setParentBusy]);
  const titles: Record<string, string> = { edit_session: 'Correct date / time', cancel_session: session?.cancelled ? 'Restore practice party' : 'Cancel practice party', attendance: 'Record free attendance', donation: 'Record donation', void_attendance: 'Correct attendance', edit_donation: 'Edit donation', delete_donation: 'Delete donation', handover: payment?.givenToSchool ? 'Undo school transfer' : 'Give donation to school' };
  const needsReason = ['edit_session', 'cancel_session', 'void_attendance'].includes(kind);
  const money = ['donation', 'edit_donation'].includes(kind) || (kind === 'attendance' && data.permissions.finance);
  return <form ref={form} aria-label={titles[kind]} className="scroll-mt-24 space-y-4 rounded-xl border-2 border-lime-500 bg-white p-5 shadow-sm" onSubmit={e => { e.preventDefault(); void mutation.save({ action: kind, revision: data.party.revision, session: schedule, studentId: student?.id, attendanceId: student?.attendanceId, paymentId: payment?.id, cancelled: !data.party.cancelled, givenToSchool: !payment?.givenToSchool, amount, paidOn: date, notes: reason, reason }); }}>
    <h2 className="text-xl">{titles[kind]}{student ? ` · ${student.firstName} ${student.lastName}` : ''}</h2><fieldset disabled={mutation.busy || mutation.uncertain} className="space-y-4 font-sans text-sm">
      {kind === 'edit_session' && <SessionFields value={schedule} onChange={setSchedule} />}
      {kind === 'void_attendance' && <p>Remove this attendance from the active roster while keeping its correction history. Donations will be kept.</p>}
      {kind === 'cancel_session' && <p>Attendance and donations will be preserved.</p>}
      {kind === 'delete_donation' && <p>Delete the {formatMoney(payment!.amountMinor)} donation for {payment!.studentName}? Attendance will be kept.</p>}
      {kind === 'handover' && <p>{payment!.givenToSchool ? 'Mark this donation as not yet given to the school.' : `Confirm ${formatMoney(payment!.amountMinor)} was given to the school.`}</p>}
      {money && <><label className="block">{kind === 'attendance' ? 'Optional donation (RON) — leave empty for attendance only' : 'Donation amount (RON)'}<input required={kind !== 'attendance'} inputMode="decimal" pattern="[0-9]{1,6}([.,][0-9]{1,2})?" className={input} value={amount} onChange={e => setAmount(e.target.value)} /></label><label className="block">Payment date<input required type="date" min="1900-01-01" max={schoolToday()} className={input} value={date} onChange={e => setDate(e.target.value)} /></label></>}
      {(needsReason || money || kind === 'attendance') && <label className="block">{needsReason ? 'Reason (required)' : 'Notes (optional)'}<textarea required={needsReason} maxLength={1000} className={input} value={reason} onChange={e => setReason(e.target.value)} /></label>}
    </fieldset>{mutation.error && <p role="alert" className="text-red-700">{mutation.error}</p>}{mutation.uncertain && <p>Retry sends the same details to avoid duplicates. Close and inspect history before starting another entry.</p>}
    <div className="flex gap-3"><button className={primary} disabled={mutation.busy}>{mutation.busy ? 'Saving…' : mutation.uncertain ? 'Retry same save' : kind === 'delete_donation' ? 'Confirm delete donation' : 'Confirm save'}</button><button type="button" className={button} disabled={mutation.busy} onClick={close}>Cancel / reload</button></div>
  </form>;
}
