CREATE TABLE IF NOT EXISTS admin_profiles (
  email TEXT PRIMARY KEY COLLATE NOCASE,
  name TEXT NOT NULL,
  picture TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
