-- Occurrences are separate from rule definitions. Birthdays retain only events
-- that entered the eligible window; transient rules can store state on demand.
CREATE TABLE task_rule_state (
  rule_key TEXT PRIMARY KEY CHECK (length(rule_key) BETWEEN 1 AND 80),
  activated_on TEXT NOT NULL CHECK (length(activated_on) = 10 AND date(activated_on, '+0 days') IS NOT NULL AND date(activated_on, '+0 days') = activated_on),
  evaluated_on TEXT NOT NULL CHECK (length(evaluated_on) = 10 AND date(evaluated_on, '+0 days') IS NOT NULL AND date(evaluated_on, '+0 days') = evaluated_on AND evaluated_on >= activated_on)
);
CREATE TABLE automatic_task_occurrences (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  rule_key TEXT NOT NULL CHECK (length(rule_key) BETWEEN 1 AND 80),
  subject_key TEXT NOT NULL CHECK (length(subject_key) BETWEEN 1 AND 200),
  occurrence_key TEXT NOT NULL CHECK (length(occurrence_key) BETWEEN 1 AND 200),
  student_id INTEGER REFERENCES students(id) ON DELETE RESTRICT,
  unlinked INTEGER NOT NULL DEFAULT 0 CHECK (unlinked IN (0, 1) AND (unlinked = 0 OR student_id IS NULL)),
  title TEXT NOT NULL CHECK (length(trim(title)) BETWEEN 1 AND 200),
  description TEXT NOT NULL DEFAULT '' CHECK (length(description) <= 10000),
  due_date TEXT CHECK (due_date IS NULL OR (due_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' AND date(due_date, '+0 days') IS NOT NULL AND date(due_date, '+0 days') = due_date)),
  status TEXT NOT NULL DEFAULT 'todo' CHECK (status IN ('todo', 'in_progress', 'done')),
  dismissed INTEGER NOT NULL DEFAULT 0 CHECK (dismissed IN (0, 1)),
  sort_order INTEGER NOT NULL CHECK (typeof(sort_order) = 'integer' AND sort_order >= 0),
  created_by TEXT COLLATE NOCASE REFERENCES admin_profiles(email),
  created_at TEXT NOT NULL,
  updated_by TEXT COLLATE NOCASE REFERENCES admin_profiles(email),
  updated_at TEXT NOT NULL,
  UNIQUE (rule_key, subject_key, occurrence_key)
);
CREATE INDEX automatic_tasks_student_idx ON automatic_task_occurrences(student_id);
CREATE INDEX automatic_tasks_order_idx ON automatic_task_occurrences(status, sort_order, id);
CREATE INDEX automatic_tasks_due_idx ON automatic_task_occurrences(due_date, status);
CREATE TRIGGER automatic_tasks_insert_revision AFTER INSERT ON automatic_task_occurrences
BEGIN UPDATE task_board_state SET revision = revision + 1 WHERE id = 1; END;
CREATE TRIGGER automatic_tasks_update_revision AFTER UPDATE ON automatic_task_occurrences
BEGIN UPDATE task_board_state SET revision = revision + 1 WHERE id = 1; END;
CREATE TRIGGER automatic_tasks_delete_revision AFTER DELETE ON automatic_task_occurrences
BEGIN UPDATE task_board_state SET revision = revision + 1 WHERE id = 1; END;
CREATE TRIGGER task_rule_insert_revision AFTER INSERT ON task_rule_state
BEGIN UPDATE task_board_state SET revision = revision + 1 WHERE id = 1; END;
CREATE TRIGGER task_rule_update_revision AFTER UPDATE ON task_rule_state
BEGIN UPDATE task_board_state SET revision = revision + 1 WHERE id = 1; END;
CREATE TRIGGER task_rule_delete_revision AFTER DELETE ON task_rule_state
BEGIN UPDATE task_board_state SET revision = revision + 1 WHERE id = 1; END;
-- Source changes invalidate any concurrent evaluation snapshot, including the
-- first activation. No task content is generated by database triggers.
CREATE TRIGGER task_student_insert_revision AFTER INSERT ON students
BEGIN UPDATE task_board_state SET revision = revision + 1 WHERE id = 1; END;
CREATE TRIGGER task_student_delete_revision AFTER DELETE ON students
BEGIN UPDATE task_board_state SET revision = revision + 1 WHERE id = 1; END;
CREATE TRIGGER task_student_update_revision AFTER UPDATE OF birth_date, active, first_name, last_name ON students
WHEN NEW.birth_date IS NOT OLD.birth_date OR NEW.active IS NOT OLD.active OR NEW.first_name IS NOT OLD.first_name OR NEW.last_name IS NOT OLD.last_name
BEGIN UPDATE task_board_state SET revision = revision + 1 WHERE id = 1; END;
