import type { Metadata, Viewport } from "next";
import { cookies } from "next/headers";
import AppShell from "./components/app-shell";
import globalStyles from "./globals.css?inline";

export const metadata: Metadata = {
  title: "vinext on Cloudflare Workers",
  description: "Generated by create-vinext-app",
  icons: {
    icon: "/logo.svg",
    shortcut: "/logo.svg",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const initialDesktopSidebarOpen = (await cookies()).get("fsd-desktop-sidebar-open")?.value !== "false";
  return (
    <html className="scroll-smooth" lang="en">
      <head><style dangerouslySetInnerHTML={{ __html: globalStyles }} /></head>
      <body className="min-w-80 bg-stone-50 font-serif text-slate-800"><AppShell initialDesktopSidebarOpen={initialDesktopSidebarOpen}>{children}</AppShell></body>
    </html>
  );
}
