import type { Metadata } from "next";
import AppShell from "./components/app-shell";
import globalStyles from "./globals.css?inline";

export const metadata: Metadata = {
  title: "vinext on Cloudflare Workers",
  description: "Generated by create-vinext-app",
  icons: {
    icon: "/logo.svg",
    shortcut: "/logo.svg",
  },
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html className="scroll-smooth" lang="en">
      <head><style dangerouslySetInnerHTML={{ __html: globalStyles }} /></head>
      <body className="min-w-80 bg-[#f7f8f6] font-serif text-[#20262d]"><AppShell>{children}</AppShell></body>
    </html>
  );
}
